import type { NotificationTask } from './types';

export const mockNotificationTasks: NotificationTask[] = [
  {
    id: 'n1',
    store_id: 'store_demo',
    type: 'daily_task_summary',
    title: '오늘 챙길 단골 업무가 정리됐어요',
    body: '이번 주 챙길 고객 28명, 오늘 보낼 메시지 9건이 준비돼 있어요.',
    payload: { visit_due: 28, pending_msg: 9 },
    target_url: '/dashboard',
    channel: 'kakao',
    scheduled_for: '2026-06-18',
    created_at: '2026-06-18T12:00:00+09:00',
    sent_at: null,
    read_at: null,
  },
  {
    id: 'n2',
    store_id: 'store_demo',
    type: 'ai_message_review_required',
    title: '승인 기다리는 AI 메시지 9건',
    body: 'AI가 준비한 재방문 메시지 9건이 승인을 기다리고 있어요. 확인 후 보내주세요.',
    payload: { pending_msg: 9 },
    target_url: '/dashboard#ai-messages',
    channel: 'kakao',
    scheduled_for: '2026-06-18',
    created_at: '2026-06-18T12:00:00+09:00',
    sent_at: null,
    read_at: null,
  },
  {
    id: 'n3',
    store_id: 'store_demo',
    type: 'inactive_customer_warning',
    title: '한동안 안 오신 고객 4명',
    body: '재방문 시점이 지난 단골 4명이 있어요. 잊기 전에 먼저 연락해보세요.',
    payload: { inactive: 4 },
    target_url: '/dashboard#visit-list',
    channel: 'kakao',
    scheduled_for: '2026-06-18',
    created_at: '2026-06-18T12:00:00+09:00',
    sent_at: null,
    read_at: null,
  },
];
