-- P0 privacy hardening for owner PIN sessions and public QR RPCs.
-- Additive migration with no destructive data operation.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.owner_credentials (
  store_id uuid primary key references public.stores(id),
  owner_id uuid not null references public.owners(id),
  pin_hash text not null,
  is_active boolean not null default true,
  pin_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.owner_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.owners(id),
  store_id uuid not null references public.stores(id),
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint owner_sessions_expiry_check check (expires_at > created_at)
);

create table if not exists public.owner_login_attempts (
  id bigint generated by default as identity primary key,
  store_id uuid references public.stores(id),
  store_key_hash text not null,
  ip_hash text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists owner_sessions_active_idx
  on public.owner_sessions(token_hash, expires_at)
  where revoked_at is null;

create index if not exists owner_login_attempts_ip_idx
  on public.owner_login_attempts(ip_hash, attempted_at desc);

create index if not exists owner_login_attempts_store_idx
  on public.owner_login_attempts(store_key_hash, attempted_at desc);

alter table public.owner_credentials enable row level security;
alter table public.owner_sessions enable row level security;
alter table public.owner_login_attempts enable row level security;

create or replace function public.owner_set_pin(
  p_store_code text,
  p_pin text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_store public.stores%rowtype;
begin
  if coalesce(p_pin, '') !~ '^[0-9]{6}$' then
    raise exception 'PIN must contain exactly six digits.';
  end if;

  select *
  into v_store
  from public.stores
  where store_id = btrim(coalesce(p_store_code, ''))
    and coalesce(status, 'active') = 'active';

  if not found then
    raise exception 'Store not found.';
  end if;

  insert into public.owner_credentials (
    store_id,
    owner_id,
    pin_hash,
    is_active,
    pin_updated_at,
    updated_at
  )
  values (
    v_store.id,
    v_store.owner_id,
    extensions.crypt(p_pin, extensions.gen_salt('bf', 12)),
    true,
    now(),
    now()
  )
  on conflict (store_id) do update
  set
    owner_id = excluded.owner_id,
    pin_hash = excluded.pin_hash,
    is_active = true,
    pin_updated_at = now(),
    updated_at = now();

  update public.owner_sessions
  set revoked_at = now()
  where store_id = v_store.id
    and revoked_at is null;
end;
$$;

create or replace function public.owner_pin_login(
  p_store_code text,
  p_pin text,
  p_store_key_hash text,
  p_ip_hash text,
  p_token_hash text,
  p_expires_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_store public.stores%rowtype;
  v_credential public.owner_credentials%rowtype;
  v_recent_failures integer;
begin
  if length(coalesce(p_store_key_hash, '')) <> 64
    or length(coalesce(p_ip_hash, '')) <> 64
    or length(coalesce(p_token_hash, '')) <> 64 then
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;

  select count(*)::integer
  into v_recent_failures
  from public.owner_login_attempts
  where succeeded = false
    and attempted_at >= now() - interval '15 minutes'
    and (ip_hash = p_ip_hash or store_key_hash = p_store_key_hash);

  if v_recent_failures >= 5 then
    insert into public.owner_login_attempts (
      store_key_hash, ip_hash, succeeded
    ) values (
      p_store_key_hash, p_ip_hash, false
    );

    return jsonb_build_object('ok', false, 'code', 'RATE_LIMITED');
  end if;

  select *
  into v_store
  from public.stores
  where store_id = btrim(coalesce(p_store_code, ''))
    and coalesce(status, 'active') = 'active';

  if found then
    select *
    into v_credential
    from public.owner_credentials
    where store_id = v_store.id
      and owner_id = v_store.owner_id
      and is_active = true;
  end if;

  if v_store.id is null
    or v_credential.store_id is null
    or coalesce(p_pin, '') !~ '^[0-9]{6}$'
    or extensions.crypt(p_pin, v_credential.pin_hash) <> v_credential.pin_hash then
    insert into public.owner_login_attempts (
      store_id, store_key_hash, ip_hash, succeeded
    ) values (
      v_store.id, p_store_key_hash, p_ip_hash, false
    );

    return jsonb_build_object('ok', false, 'code', 'INVALID_CREDENTIALS');
  end if;

  if p_expires_at <= now()
    or p_expires_at > now() + interval '30 minutes' then
    return jsonb_build_object('ok', false, 'code', 'INVALID_EXPIRY');
  end if;

  update public.owner_sessions
  set revoked_at = now()
  where store_id = v_store.id
    and revoked_at is null;

  insert into public.owner_sessions (
    owner_id, store_id, token_hash, expires_at
  ) values (
    v_store.owner_id, v_store.id, p_token_hash, p_expires_at
  );

  insert into public.owner_login_attempts (
    store_id, store_key_hash, ip_hash, succeeded
  ) values (
    v_store.id, p_store_key_hash, p_ip_hash, true
  );

  return jsonb_build_object(
    'ok', true,
    'store_name', v_store.name,
    'expires_at', p_expires_at
  );
end;
$$;

create or replace function public.owner_session_dashboard(p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.owner_sessions%rowtype;
  v_store public.stores%rowtype;
begin
  select s.*
  into v_session
  from public.owner_sessions s
  join public.owner_credentials c
    on c.store_id = s.store_id
   and c.owner_id = s.owner_id
   and c.is_active = true
  where s.token_hash = p_token_hash
    and s.revoked_at is null
    and s.expires_at > now();

  if not found then
    return jsonb_build_object('ok', false, 'code', 'SESSION_INVALID');
  end if;

  select *
  into v_store
  from public.stores
  where id = v_session.store_id
    and owner_id = v_session.owner_id
    and coalesce(status, 'active') = 'active';

  if not found then
    return jsonb_build_object('ok', false, 'code', 'SESSION_INVALID');
  end if;

  update public.owner_sessions
  set last_seen_at = now()
  where id = v_session.id;

  return jsonb_build_object(
    'ok', true,
    'snapshot', public.qr_owner_dashboard_snapshot(v_store.store_id),
    'expires_at', v_session.expires_at
  );
end;
$$;

create or replace function public.owner_session_logout(p_token_hash text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.owner_sessions
  set revoked_at = now()
  where token_hash = p_token_hash
    and revoked_at is null;
$$;

create or replace function public.qr_customer_lookup(
  p_store_id text,
  p_phone text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_store public.stores%rowtype;
  v_phone text;
  v_exists boolean;
begin
  select *
  into v_store
  from public.stores
  where store_id = btrim(coalesce(p_store_id, ''))
    and coalesce(status, 'active') = 'active';

  if not found then
    raise exception 'Store not found.';
  end if;

  if p_phone is null then
    return jsonb_build_object('mode', 'store', 'store_name', v_store.name);
  end if;

  v_phone := public.normalize_customer_phone(p_phone);
  if length(v_phone) not in (10, 11) then
    raise exception 'Invalid phone number.';
  end if;

  select exists (
    select 1
    from public.customers
    where store_id = v_store.id
      and phone = v_phone
  ) into v_exists;

  return jsonb_build_object(
    'mode', case when v_exists then 'existing' else 'new' end,
    'store_name', v_store.name
  );
end;
$$;

create or replace function public.qr_customer_checkin(
  p_store_id text,
  p_phone text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_store public.stores%rowtype;
  v_phone text;
  v_customer public.customers%rowtype;
  v_now timestamptz := now();
  v_last_visit_at timestamptz;
  v_visit_count integer;
begin
  select *
  into v_store
  from public.stores
  where store_id = btrim(coalesce(p_store_id, ''))
    and coalesce(status, 'active') = 'active';

  if not found then
    raise exception 'Store not found.';
  end if;

  v_phone := public.normalize_customer_phone(p_phone);
  if length(v_phone) not in (10, 11) then
    raise exception 'Invalid phone number.';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(v_store.id::text || ':' || v_phone, 0)
  );

  select *
  into v_customer
  from public.customers
  where store_id = v_store.id
    and phone = v_phone;

  if not found then
    return jsonb_build_object('mode', 'not_registered', 'store_name', v_store.name);
  end if;

  select max(visit_date)
  into v_last_visit_at
  from public.visits
  where store_id = v_store.id
    and customer_id = v_customer.id;

  if v_last_visit_at is not null
    and v_last_visit_at > v_now - interval '6 hours' then
    return jsonb_build_object('mode', 'already_checked_in', 'store_name', v_store.name);
  end if;

  insert into public.visits (
    customer_id, store_id, visit_date, visit_source
  ) values (
    v_customer.id, v_store.id, v_now, 'qr_checkin'
  );

  select count(*)::integer, max(visit_date)
  into v_visit_count, v_last_visit_at
  from public.visits
  where store_id = v_store.id
    and customer_id = v_customer.id;

  update public.customers
  set visit_count = v_visit_count,
      last_visit_at = v_last_visit_at,
      updated_at = v_now
  where id = v_customer.id;

  return jsonb_build_object('mode', 'checked_in', 'store_name', v_store.name);
end;
$$;

create or replace function public.qr_customer_register(
  p_store_id text,
  p_phone text,
  p_name text,
  p_consent boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_store public.stores%rowtype;
  v_phone text;
  v_name text;
  v_customer_id uuid;
  v_now timestamptz := now();
begin
  select *
  into v_store
  from public.stores
  where store_id = btrim(coalesce(p_store_id, ''))
    and coalesce(status, 'active') = 'active';

  if not found then
    raise exception 'Store not found.';
  end if;

  v_phone := public.normalize_customer_phone(p_phone);
  v_name := btrim(coalesce(p_name, ''));

  if length(v_phone) not in (10, 11) or v_name = '' then
    raise exception 'Invalid registration request.';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(v_store.id::text || ':' || v_phone, 0)
  );

  select id
  into v_customer_id
  from public.customers
  where store_id = v_store.id
    and phone = v_phone;

  if found then
    return public.qr_customer_checkin(p_store_id, v_phone);
  end if;

  insert into public.customers (
    store_id, name, phone, privacy_agreed, marketing_agreed, consent,
    visit_count, last_visit_at, status, created_at, updated_at
  ) values (
    v_store.id, v_name, v_phone, true, coalesce(p_consent, false),
    coalesce(p_consent, false), 1, v_now, 'new', v_now, v_now
  ) returning id into v_customer_id;

  insert into public.visits (
    customer_id, store_id, visit_date, visit_source
  ) values (
    v_customer_id, v_store.id, v_now, 'qr_register'
  );

  return jsonb_build_object('mode', 'registered', 'store_name', v_store.name);
end;
$$;

revoke all on function public.owner_set_pin(text, text) from public, anon, authenticated;
revoke all on function public.owner_pin_login(text, text, text, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.owner_session_dashboard(text) from public, anon, authenticated;
revoke all on function public.owner_session_logout(text) from public, anon, authenticated;
revoke all on function public.qr_owner_dashboard_snapshot(text) from public, anon, authenticated;

grant execute on function public.owner_set_pin(text, text) to service_role;
grant execute on function public.owner_pin_login(text, text, text, text, text, timestamptz) to service_role;
grant execute on function public.owner_session_dashboard(text) to service_role;
grant execute on function public.owner_session_logout(text) to service_role;
grant execute on function public.qr_owner_dashboard_snapshot(text) to service_role;

revoke all on function public.qr_customer_lookup(text, text) from public;
revoke all on function public.qr_customer_register(text, text, text, boolean) from public;
revoke all on function public.qr_customer_checkin(text, text) from public;

grant execute on function public.qr_customer_lookup(text, text) to anon, authenticated;
grant execute on function public.qr_customer_register(text, text, text, boolean) to anon, authenticated;
grant execute on function public.qr_customer_checkin(text, text) to anon, authenticated;
