-- Secure operator sessions and owner PIN issuance.
-- Additive only: no DROP, DELETE, TRUNCATE, or customer data changes.

create table if not exists public.operator_sessions (
  id uuid primary key default gen_random_uuid(),
  operator_email text not null,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint operator_sessions_expiry_check check (expires_at > created_at)
);

create table if not exists public.operator_login_attempts (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  ip_hash text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

create table if not exists public.operator_pin_audit (
  id bigint generated by default as identity primary key,
  operator_email text not null,
  store_id uuid not null references public.stores(id),
  store_code text not null,
  action text not null,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint operator_pin_audit_action_check check (action in ('issued', 'reissued')),
  constraint operator_pin_audit_reason_check check (reason in ('initial_issue', 'forgot_pin', 'security_reset'))
);

create index if not exists operator_sessions_active_idx
  on public.operator_sessions(token_hash, expires_at)
  where revoked_at is null;

create index if not exists operator_login_attempts_lookup_idx
  on public.operator_login_attempts(email_hash, ip_hash, attempted_at desc);

create index if not exists operator_pin_audit_store_idx
  on public.operator_pin_audit(store_id, created_at desc);

alter table public.operator_sessions enable row level security;
alter table public.operator_login_attempts enable row level security;
alter table public.operator_pin_audit enable row level security;

create or replace function public.operator_login_allowed(
  p_email_hash text,
  p_ip_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recent_failures integer;
begin
  if length(coalesce(p_email_hash, '')) <> 64
    or length(coalesce(p_ip_hash, '')) <> 64 then
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;

  select count(*)::integer
  into v_recent_failures
  from public.operator_login_attempts
  where succeeded = false
    and attempted_at >= now() - interval '15 minutes'
    and (email_hash = p_email_hash or ip_hash = p_ip_hash);

  return jsonb_build_object(
    'ok', v_recent_failures < 5,
    'code', case when v_recent_failures < 5 then 'ALLOWED' else 'RATE_LIMITED' end
  );
end;
$$;

create or replace function public.operator_login_failed(
  p_email_hash text,
  p_ip_hash text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if length(coalesce(p_email_hash, '')) <> 64
    or length(coalesce(p_ip_hash, '')) <> 64 then
    raise exception 'Invalid login attempt.';
  end if;

  insert into public.operator_login_attempts(email_hash, ip_hash, succeeded)
  values (p_email_hash, p_ip_hash, false);
end;
$$;

create or replace function public.operator_session_create(
  p_operator_email text,
  p_token_hash text,
  p_expires_at timestamptz,
  p_email_hash text,
  p_ip_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if btrim(coalesce(p_operator_email, '')) = ''
    or length(coalesce(p_token_hash, '')) <> 64
    or length(coalesce(p_email_hash, '')) <> 64
    or length(coalesce(p_ip_hash, '')) <> 64
    or p_expires_at <= now()
    or p_expires_at > now() + interval '2 hours' then
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;

  update public.operator_sessions
  set revoked_at = now()
  where lower(operator_email) = lower(p_operator_email)
    and revoked_at is null;

  insert into public.operator_sessions(operator_email, token_hash, expires_at)
  values (lower(p_operator_email), p_token_hash, p_expires_at);

  insert into public.operator_login_attempts(email_hash, ip_hash, succeeded)
  values (p_email_hash, p_ip_hash, true);

  return jsonb_build_object(
    'ok', true,
    'operator_email', lower(p_operator_email),
    'expires_at', p_expires_at
  );
end;
$$;

create or replace function public.operator_session_validate(p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.operator_sessions%rowtype;
begin
  if length(coalesce(p_token_hash, '')) <> 64 then
    return jsonb_build_object('ok', false);
  end if;

  select *
  into v_session
  from public.operator_sessions
  where token_hash = p_token_hash
    and revoked_at is null
    and expires_at > now();

  if not found then
    return jsonb_build_object('ok', false);
  end if;

  update public.operator_sessions
  set last_seen_at = now()
  where id = v_session.id;

  return jsonb_build_object(
    'ok', true,
    'operator_email', v_session.operator_email,
    'expires_at', v_session.expires_at
  );
end;
$$;

create or replace function public.operator_session_logout(p_token_hash text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.operator_sessions
  set revoked_at = now()
  where token_hash = p_token_hash
    and revoked_at is null;
end;
$$;

create or replace function public.operator_list_stores(p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.operator_sessions%rowtype;
  v_stores jsonb;
begin
  select *
  into v_session
  from public.operator_sessions
  where token_hash = p_token_hash
    and revoked_at is null
    and expires_at > now();

  if not found then
    return jsonb_build_object('ok', false);
  end if;

  update public.operator_sessions set last_seen_at = now() where id = v_session.id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'store_id', s.store_id,
    'store_name', s.name,
    'owner_name', o.name,
    'phone', s.phone,
    'address', s.address,
    'industry', s.industry,
    'status', coalesce(s.status, 'active'),
    'created_at', s.created_at,
    'pin_configured', (c.store_id is not null),
    'pin_updated_at', c.pin_updated_at
  ) order by s.created_at desc), '[]'::jsonb)
  into v_stores
  from public.stores s
  left join public.owners o on o.id = s.owner_id
  left join public.owner_credentials c on c.store_id = s.id;

  return jsonb_build_object('ok', true, 'stores', v_stores);
end;
$$;

create or replace function public.operator_issue_owner_pin(
  p_token_hash text,
  p_store_code text,
  p_pin text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_session public.operator_sessions%rowtype;
  v_store public.stores%rowtype;
  v_had_pin boolean;
  v_action text;
begin
  select *
  into v_session
  from public.operator_sessions
  where token_hash = p_token_hash
    and revoked_at is null
    and expires_at > now();

  if not found then
    return jsonb_build_object('ok', false, 'code', 'UNAUTHORIZED');
  end if;

  if coalesce(p_pin, '') !~ '^[0-9]{6}$'
    or p_reason not in ('initial_issue', 'forgot_pin', 'security_reset') then
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;

  select *
  into v_store
  from public.stores
  where store_id = btrim(coalesce(p_store_code, ''))
    and coalesce(status, 'active') = 'active';

  if not found then
    return jsonb_build_object('ok', false, 'code', 'STORE_NOT_FOUND');
  end if;

  select exists(
    select 1 from public.owner_credentials where store_id = v_store.id
  ) into v_had_pin;

  perform public.owner_set_pin(v_store.store_id, p_pin);
  v_action := case when v_had_pin then 'reissued' else 'issued' end;

  insert into public.operator_pin_audit(
    operator_email, store_id, store_code, action, reason
  ) values (
    v_session.operator_email, v_store.id, v_store.store_id, v_action, p_reason
  );

  update public.operator_sessions set last_seen_at = now() where id = v_session.id;

  return jsonb_build_object(
    'ok', true,
    'action', v_action,
    'store_id', v_store.store_id,
    'store_name', v_store.name
  );
end;
$$;

revoke all on table public.operator_sessions from public, anon, authenticated;
revoke all on table public.operator_login_attempts from public, anon, authenticated;
revoke all on table public.operator_pin_audit from public, anon, authenticated;

revoke all on function public.operator_login_allowed(text, text) from public, anon, authenticated;
revoke all on function public.operator_login_failed(text, text) from public, anon, authenticated;
revoke all on function public.operator_session_create(text, text, timestamptz, text, text) from public, anon, authenticated;
revoke all on function public.operator_session_validate(text) from public, anon, authenticated;
revoke all on function public.operator_session_logout(text) from public, anon, authenticated;
revoke all on function public.operator_list_stores(text) from public, anon, authenticated;
revoke all on function public.operator_issue_owner_pin(text, text, text, text) from public, anon, authenticated;

grant execute on function public.operator_login_allowed(text, text) to service_role;
grant execute on function public.operator_login_failed(text, text) to service_role;
grant execute on function public.operator_session_create(text, text, timestamptz, text, text) to service_role;
grant execute on function public.operator_session_validate(text) to service_role;
grant execute on function public.operator_session_logout(text) to service_role;
grant execute on function public.operator_list_stores(text) to service_role;
grant execute on function public.operator_issue_owner_pin(text, text, text, text) to service_role;
